name: 'Playwright GitHub Action'
description: 'GitHub Action that helps you run your playwright tests'
branding:
  icon: at-sign
  color: green
runs:
  using: 'docker'
  image: 'docker://ghcr.io/7th-green/gha-playwright:latest'
